stm32_bridge:
  ros__parameters:
    base_frame: base_link
    baud_rate: 115200
    cmd_rate: 100.0
    cmd_timeout_ms: 200
    counts_per_rev: 1560
    max_angular_vel: 2.0
    max_linear_vel: 0.5
    odom_frame: odom
    publish_rate: 50.0
    serial_port: /dev/ttyS1
    wheel_base: 0.2692
    wheel_circumference: 0.241
