ydlidar_ros2_driver_node:
  ros__parameters:
    port: /dev/ttyUSB0
    frame_id: laser_frame
    ignore_array: ""
    baudrate: 230400
    lidar_type: 1
    device_type: 0
    sample_rate: 9               # 9KHz (最大, 提高扫描分辨率)
    intensity_bit: 0
    abnormal_check_count: 4
    fixed_resolution: true
    reversion: true
    inverted: true
    auto_reconnect: true
    isSingleChannel: true
    intensity: false
    support_motor_dtr: true
    angle_max: 180.0
    angle_min: -180.0
    range_max: 12.0               # 室内用 12m 够了, 减少噪点
    range_min: 0.1                # 过滤近距离自干扰
    frequency: 12.0               # 提到 12Hz (更快的扫描更新)
    invalid_range_is_inf: false
